name: SAST
on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep --config p/default  --config p/security-audit --config rules/custom.yml --sarif --output semgrep.sarif .
          semgrep --config p/default  --severity ERROR --error .
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
